"#include <torch/extension.h>\n",
        "#include <cuda_runtime.h>\n",
        "#include <math.h>\n",
        "__global__ void qk_k(const float* Q,const float* K,float* S,int N,int dk,float sc){\n",
        "    int b=blockIdx.z,row=blockIdx.y*16+threadIdx.y,col=blockIdx.x*16+threadIdx.x;\n",
        "    if(row>=N||col>=N) return;\n",
        "    float a=0; for(int k=0;k<dk;k++) a+=Q[b*N*dk+row*dk+k]*K[b*N*dk+col*dk+k];\n",
        "    S[b*N*N+row*N+col]=a*sc;\n",
        "}\n",
        "__global__ void sm_k(float* S,int B,int N){\n",
        "    int b=blockIdx.y,row=blockIdx.x*256+threadIdx.x;\n",
        "    if(row>=N) return;\n",
        "    float* r=S+b*N*N+row*N;\n",
        "    float mx=r[0]; for(int i=1;i<N;i++) mx=fmaxf(mx,r[i]);\n",
        "    float s=0; for(int i=0;i<N;i++){r[i]=expf(r[i]-mx);s+=r[i];}\n",
        "    for(int i=0;i<N;i++) r[i]/=s;\n",
        "}\n",
        "__global__ void pv_k(const float* P,const float* V,float* O,int N,int dk){\n",
        "    int b=blockIdx.z,row=blockIdx.y*16+threadIdx.y,col=blockIdx.x*16+threadIdx.x;\n",
        "    if(row>=N||col>=dk) return;\n",
        "    float a=0; for(int k=0;k<N;k++) a+=P[b*N*N+row*N+k]*V[b*N*dk+k*dk+col];\n",
        "    O[b*N*dk+row*dk+col]=a;\n",
        "}\n",
        "torch::Tensor naive_attention(torch::Tensor Q,torch::Tensor K,torch::Tensor V){\n",
        "    int B=Q.size(0),N=Q.size(1),dk=Q.size(2);\n",
        "    float sc=1.0f/sqrtf((float)dk);\n",
        "    auto S=torch::empty({B,N,N},Q.options());\n",
        "    auto O=torch::empty({B,N,dk},Q.options());\n",
        "    dim3 t2(16,16);\n",
        "    qk_k<<<dim3((N+15)/16,(N+15)/16,B),t2>>>(Q.data_ptr<float>(),K.data_ptr<float>(),S.data_ptr<float>(),N,dk,sc);\n",
        "    sm_k<<<dim3((N+255)/256,B),256>>>(S.data_ptr<float>(),B,N);\n",
        "    pv_k<<<dim3((dk+15)/16,(N+15)/16,B),t2>>>(S.data_ptr<float>(),V.data_ptr<float>(),O.data_ptr<float>(),N,dk);\n",
        "    return O;\n",
        "}\n",