"#include <torch/extension.h>\n",
        "#include <cuda_runtime.h>\n",
        "#include <math.h>\n",
        "#define TS 16\n",
        "\n",
        "__global__ void tiled_k(const float* Q,const float* K,const float* V,float* O,\n",
        "                         int N,int dk,float scale){\n",
        "    int b=blockIdx.z, qi=blockIdx.x*TS+threadIdx.x;\n",
        "    bool valid_q = (qi < N);\n",
        "\n",
        "    float q[16]={};\n",
        "    if(valid_q)\n",
        "        for(int d=0;d<dk;d++) q[d]=Q[b*N*dk+qi*dk+d];\n",
        "\n",
        "    float o[16]={}, m_prev=-1e9f, l_prev=0.0f;\n",
        "    __shared__ float Ks[TS][16], Vs[TS][16];\n",
        "\n",
        "    int nt=(N+TS-1)/TS;\n",
        "    for(int t=0;t<nt;t++){\n",
        "        // ALL threads participate in loading -- no early return above\n",
        "        int ki=t*TS+threadIdx.x;\n",
        "        if(ki<N){\n",
        "            for(int d=0;d<dk;d++){\n",
        "                Ks[threadIdx.x][d]=K[b*N*dk+ki*dk+d];\n",
        "                Vs[threadIdx.x][d]=V[b*N*dk+ki*dk+d];\n",
        "            }\n",
        "        } else {\n",
        "            for(int d=0;d<dk;d++){ Ks[threadIdx.x][d]=0; Vs[threadIdx.x][d]=0; }\n",
        "        }\n",
        "        __syncthreads();\n",
        "\n",
        "        if(valid_q){\n",
        "            int te=min(TS,N-t*TS);\n",
        "            float m_tile=-1e9f;\n",
        "            for(int j=0;j<te;j++){\n",
        "                float s=0;\n",
        "                for(int d=0;d<dk;d++) s+=q[d]*Ks[j][d];\n",
        "                s*=scale;\n",
        "                m_tile=fmaxf(m_tile,s);\n",
        "            }\n",
        "            float m_new=fmaxf(m_prev,m_tile);\n",
        "            float l_tile=0.0f;\n",
        "            float o_tile[16]={};\n",
        "            for(int j=0;j<te;j++){\n",
        "                float s=0;\n",
        "                for(int d=0;d<dk;d++) s+=q[d]*Ks[j][d];\n",
        "                s*=scale;\n",
        "                float es=expf(s-m_new);\n",
        "                l_tile+=es;\n",
        "                for(int d=0;d<dk;d++) o_tile[d]+=es*Vs[j][d];\n",
        "            }\n",
        "            float alpha=expf(m_prev-m_new);\n",
        "            for(int d=0;d<dk;d++) o[d]=o[d]*alpha+o_tile[d];\n",
        "            l_prev=l_prev*alpha+l_tile;\n",
        "            m_prev=m_new;\n",
        "        }\n",
        "        __syncthreads();\n",
        "    }\n",
        "\n",
        "    if(valid_q)\n",
        "        for(int d=0;d<dk;d++) O[b*N*dk+qi*dk+d]=o[d]/l_prev;\n",
        "}\n",
        "\n",
        "torch::Tensor tiled_attention(torch::Tensor Q,torch::Tensor K,torch::Tensor V){\n",
        "    int B=Q.size(0),N=Q.size(1),dk=Q.size(2);\n",
        "    auto O=torch::empty_like(Q);\n",
        "    tiled_k<<<dim3((N+TS-1)/TS,1,B),TS>>>(\n",
        "        Q.data_ptr<float>(),K.data_ptr<float>(),\n",
        "        V.data_ptr<float>(),O.data_ptr<float>(),\n",
        "        N,dk,1.0f/sqrtf((float)dk));\n",
        "    return O;\n",
        "}\n",